name: EQualificationExamModelStudy
channels:
  - conda-forge
dependencies:
  - python=3.11.11
  - pip
  - pip:
    - grad-cam==1.5.4
    - matplotlib==3.9.3
    - numpy==2.0.2
    - opencv-python==4.10.0.84
    - torch==2.5.1
    - torchinfo==1.8.0
    - torchvision==0.20.1
    - torchmetrics
    
